language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=TEST
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE IF NOT EXISTS wayfarer_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE wayfarer to admin;" -U postgres
