language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=TEST
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE wayfarer_test;" -U postgres
  - psql -U postgres wayfarer_test -c 'CREATE EXTENSION "uuid-ossp";'
  - psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE wayfarer_test to admin;" -U postgres
